# Generated by Django 3.2.2 on 2023-08-18 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 15, 3, 52, 927140, tzinfo=utc)),
        ),
    ]
