# Generated by Django 3.2.2 on 2023-08-19 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_poll_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 13, 33, 573044, tzinfo=utc)),
        ),
    ]
