# Generated by Django 3.2.2 on 2023-05-18 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_auto_20230517_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='userAPI.UserAccount'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 21, 29, 8, 147725, tzinfo=utc)),
        ),
    ]
