# Generated by Django 3.2.2 on 2023-08-19 13:30

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_poll_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='expo_push_token',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='expo_push_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 13, 30, 40, 721328, tzinfo=utc)),
        ),
    ]
