# Generated by Django 3.2.2 on 2023-08-19 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_auto_20230819_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 13, 32, 58, 859819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='expo_push_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
