# Generated by Django 3.2.2 on 2023-08-19 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_alter_poll_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='expo_push_tokens',
            new_name='expo_push_token',
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 18, 50, 187974, tzinfo=utc)),
        ),
    ]
