# Generated by Django 3.2.2 on 2023-08-19 13:50

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_auto_20230819_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 13, 50, 8, 997900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='expo_push_tokens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
