# Generated by Django 3.2.2 on 2023-05-26 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_auto_20230526_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 5, 43, 19, 829388, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='FacebookUser',
        ),
    ]
