# Generated by Django 3.2.2 on 2023-05-31 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_auto_20230526_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 0, 17, 32, 492243, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='GoogleUser',
        ),
    ]
