# Generated by Django 3.2.2 on 2023-10-09 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_alter_poll_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 16, 18, 55, 860299, tzinfo=utc)),
        ),
    ]
