# Generated by Django 3.2.2 on 2023-06-12 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_auto_20230531_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 2, 53, 37, 419898, tzinfo=utc)),
        ),
    ]
