# Generated by Django 3.2.2 on 2023-07-08 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_alter_poll_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='expo_tokens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 17, 41, 26, 118204, tzinfo=utc)),
        ),
    ]
