# Generated by Django 3.2.2 on 2023-07-08 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0009_auto_20230708_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='expo_tokens',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='expo_token',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 21, 38, 22, 385463, tzinfo=utc)),
        ),
    ]
