# Generated by Django 3.2.2 on 2023-07-08 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0010_auto_20230708_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='expo_token',
            new_name='expo_push_token',
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 22, 2, 48, 375014, tzinfo=utc)),
        ),
    ]
