# Generated by Django 3.2.2 on 2023-07-23 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0013_auto_20230723_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 15, 2, 14, 472319, tzinfo=utc)),
        ),
    ]
