# Generated by Django 3.2.2 on 2023-07-24 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0017_alter_poll_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 10, 36, 52, 965291, tzinfo=utc)),
        ),
    ]
