# Generated by Django 3.2.2 on 2023-07-24 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0018_auto_20230724_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='new_id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 10, 37, 57, 310135, tzinfo=utc)),
        ),
    ]
