# Generated by Django 3.2.2 on 2023-07-24 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0019_auto_20230724_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 10, 40, 10, 449810, tzinfo=utc)),
        ),
    ]
